# Tratamento de Errors e Opcionais

Na vida, sempre vamos ter que lidar com nossos erros, na programação não é diferente. Em Rust temos vários meios de tratar nossos erros. Antes de mais nada, a linguagem divide erros em duas categorias: erros _recuperáveis_ e _irrecuperáveis_. Para os recuperáveis, temos por exemplo, um erro de _arquivo não encontrado_, é um tipo de erro que gostaria de informar o usuário sobre isso e tentar novamente, ou tomar outra ação. Para os irrecuperáveis são _sempre_ sintomas de bugs, como acesso de memória inválido, que necessita que o programa pare imediatamente.

Dito isso, a maioria das linguagens usa o mecanismo de _exceptions_, mas em Rust não fazemos isso. Em vez disso, temos o tipo `Result<T, E>` para erros recuperáveis e o macro `panic!` para parar a execução do programa quando encontramos erros irrecuperáveis.

## Erros irrecuperáveis com _panic!_

As vezes, coisas ruins acontecem, e não podemos fazer nada sobre isso. Nesse caso, as vezes o que podemos fazer é chamar o macro `panic!`. Na prática seu código pode entrar em "pânico" de dois jeitos: realizando uma ação que cause pânico (como acessar um valor fora de um array) ou chamando o macro `panic!`. Dos dois modos, uma mensagem de erro será imprimida na tela, e o stack é limpo, e o programa encerra. Hora de ver isso na prática.

``` rust
fn main() {
    panic!("KAAOS");
}
```

Rode e veja o caos acontecer. A chamada vai causar uma mensagem de erro nas últimas duas linhas, incluindo a nossa mensagem e o lugar onde o pânico foi causado. Agora vamos causar um pânico indiretamente.

``` rust
fn main() {
    let v = vec![1, 2, 3]; // macro vec!, cria um array dinâmico, veremos isso mais tarde

    v[99];
}
```

Estamos tentando acessar o centésimo elemento em um vetor de três elementos e por isso, Rust vai causar um pânico.

Para impedir que nosso código entre em pânico é sempre preciso resolver a fonte do problema e corrigí-lo.

## Erros recuperáveis com _Result_

Nem toda falha é tão extrema e é preciso matar o programa. Alguns erros têm concerto. Por exemplo, abrir um arquivo pode falhar caso o arquivo não exista, e se isso ocorrer você vai querer criá-lo. Para indicar que um código pode falhar atribuímos um tipo de retorno especial, chamado o tipo `Result`, um enum de duas variantes, `Ok` e `Err`, como segue:

``` rust
enum Result<T, E> {
    Ok(T),
    Err(E)
}
```

Onde `T` e `E` são tipos genéticos, `T` representa o valor que será retornado em caso de sucesso dentro da variância `Ok`, e `E` o valor que será retornado em caso de falha na variância de `Err`.

Vamos ver um exemplo:

```rust
// Importa a estrutura `File`, que permite manipulação de arquivos
use std:fs:File;

fn main() {
    let file = File::open("hello.txt");
}
```

`File::open` retorna um `Result<T, E>`, o tipo `T` é do tipo `File`, o tipo `E` do tipo `std::io::Error`. Caso tenhamos sucesso, teremos uma objeto para interagir com nosso arquivo, caso contrário teremos que tratar o erro. Vejamos agora como resolver essa expressão:

``` rust
use std::fs::File;

fn main() {
    let file = File::open("hello.txt");

    let file = match file {
        Ok(f) => f, // Estamos capturando e retornando f
        Err(erro) => panic!("Problema em abrir o arquivo: {erro:?}"),
    }
}
```

Nós usamos o operador `match` para _desembrulhar_ nosso `Result`, caso ele seja um `Ok<T>`, quer dizer que tivermos sucesso, e queremos pegar o valor `T` e retorná-lo. Contudo, se tivermos um erro emitimos um pânico e encerramos a execução. Claro que fazer isso não é o ideal, como foi dito na seção passada. Logo vejamos formas de lidar com os casos de erro:

``` rust
use std::fs::File;
use std::io::ErrorKind;

fn main() {
    let file = File::open("hello.txt");

    let file = match file {
        Ok(f) => f,
        Err(erro) => match erro.kind() {
            ErrorKind::NotFound => match File::create("hello.txt") {
                Ok(fc) => fc,
                Err(e) => panic!("Problema criando o arquivo: {fc:?}"),
            },
            outro_erro => {
                panic!("Problema abrindo o arquivo: {outro_erro:?}");
            }
        }
    }
}
```

O tipo `io::Error` prove um método `kind` que nos dá um enum `io::ErrorKind` com as variações possíveis de erros relacionados à entrada e saída. No exemplo acima, caso o arquivo não seja encontrado nós o criamos, se qualquer outro erro acontecer, ou se criar o arquivo falhar nós entramos em pânico.

### Atalhos para pânico com Error

O operador `match` pode ser bem _verboso_ na maioria das vezes. Assim, `Result<T, E>` possui vários métodos para escrevermos mais rápido e de modo mais claro. Apresentamos aqui duas formas: os métodos `unwrap` e `expect`, que resultam em um pânico em caso de erro. Vejamos dois exemplos.

Exemplo com `unwrap`:
``` rust
use std::fs::File;

fn main() {
    // unwrap é equivalente ao match e panic! do primeiro exemplo, caso tenhamos um erro o programa entra em pânico.
    let file = File::open("hello.txt").unwrap()
}
```

Exemplo com `expect`
``` rust
use std::fs::File;

fn main() {
    // A diferença do expect é que ele recebe uma string como argumento, e será mostrada junto com a mensagem de erro.
    // Recomenda-se que a mensagem diga o que o programador esperava acontecer
    let file = File::open("hello.txt").expect("arquivo deveria ser aberto");
}
```
> [!note] esses métodos, são ótimos para escrever um código rápido, mas não é recomendado que eles continuem até a produção (especialmente o `unwrap`), espera-se que você trate seus erros afinal. O lado bom é que você pode facilmente encontrá-los com uma busca em um arquivo, ou adicionando ao seu _linter_ para emitir avisos caso esses métodos sejam chamados.

### Propagando erros

Outra forma de lidar com nossos erros é empurrá-los para outra pessoa. Também podemos fazer isso no Rust, nossas funções vão **propagar** erros para cima até que sejam propriamente tratados (ou não). Isto é bom para centralizar a forma como tratamos erros. MAs chega de conversa, direto para o exemplo:

``` rust
use std::fs::File;
use std::io::{self, Read};

fn read_msg_from_file() -> Result<String, io::Error> {
    // Tentamos abrir o arquivo, caso falhe propagamos o erro
    let file = File::open("hello.txt");
    let file = match file {
        Ok(f) => f,
        Err(e) => return Err(e),
    };

    let mut msg = String::new();

    // Lemos o arquivo e retornamos nossa mensagem ou um erro
    match file.read_to_string(&mut msg) {
        Ok(_) => Ok(msg),
        Err(e) => Err(e)
    }
}

fn main() {
    let msg = read_msg_from_file().expect("");
    println!("{}", msg);
}
```

Podemos escrever essa função de um jeito mais curto, mas assim é melhor para entender o que está acontecendo. Simplesmente tentamos abrir um arquivo, ler seu conteúdo e retorná-lo, caso qualquer etapa falhe, retornamos um erro, caso tenhamos sucesso mostramos na tela a mensagem.

### Reduzindo o código com o operador ?

Você vai ver o seguinte padrão com bastante frequência:

``` rust
let file =  match File::open("hello.txt") {
    Ok(f) => f,
    Err(error) => return Err(error)
}
```

Se tivermos um `Ok`, atribuimos se for um `Err` retornamos. É um padrão tão comum que um operador para fazer isso foi introduzido na linguagem, o operador `?`, ele faz exatamente o que o exemplo acima faz, vejamos:

``` rust
let file = File::open("hello.txt")? // Sim, simples assim
```

Agora vejamos como escrever aquele outro exemplo de modo mais curto.
``` rust
use std::fs::File;
use std::io::{self, Read};

fn read_msg_from_file() -> Result<String, io::Error> {
    let mut msg = String::new();
    File::open("hello.txt")?.read_to_string(&mut msg)?;
    Ok(msg)
}

fn main() {
    let msg = read_msg_from_file().expect("");
    println!("{}", msg);
}
```

Excelente, economizamos muitas linhas assim, mas acho que ainda não é o bastante, podemos fazer isso em **uma única linha**, com uma função dentro da biblioteca `fs`, olha só:

``` rust
use std::fs;

fn read_msg_from_file() -> Result<String, io::Error> {
    fs::read_to_string("hello.txt") // Uau!
}

fn main() {
    let msg = read_msg_from_file().expect("");
    println!("{}", msg);
}
```

Hora de ver um último conceito: opções!

## Apresentando o tipo _Option_

Aqui vai mais um enum da biblioteca padrão: o tipo `Option<T>`, que representa o cenário em que um valor **pode conter algo ou nada**. A necessidade de representar a ausência de alguma coisa é bem comum na programação, acessar um array por exemplo, se ele estiver vazio é esperado que nada seja retornado. O tipo opcional serve justamente para esses casos, onde existe a possibilidade de não haver nada à retornar (ou haver) e queremos que o usuário do nosso código saiba disso, e trate o caso em que não haverá valor nenhum. Dito isso, vejamos a declaração de `Option<T>`:

```rust
enum Option<T> {
    Some(T),
    None
}
```

Como vemos, é um tipo bem simples, ou temos _algo_, um `Some(T)`, ou temos _nada_, `None`. Hora de olhar uns exemplos.

``` rust
fn get_from_array(arr: &[i32], index: usize) -> Option<&i32> {
    arr.get(index)
}

fn main() {
    let arr = [1, 2, 3, 4, 5, 6, 7];
    // Assert é um macro que faz uma comparação e entra em pânico se ela falhar
    assert!(None == get_from_array(&arr, 12)); // Passamos um index inexistente
    assert!(Some(&1i32) == get_from_array(&arr, 0)); // Nosso retorno vem embrulhado em um Some
}
```

Retiramos nosso valor `Some` da mesma forma que retiramos do `Ok`, inclusive o operador `?`, bem como `unwrap`, funcionam com o `Option<T>`. Em resumo, é um tipo extremamente útil no controle de fluxo do programa.

Depois de aprender tudo isso, é hora de ver sobre ferramentas que a biblioteca padrão nos disponibiliza para construirmos nossos projetos.
